# This is a basic workflow to help you get started with Actions

name: Artifact

on: [push]

env: 
  ARTIFACT_NAME: myartifact
  
jobs: 
  main: 
    runs-on: Check out the code
    steps:
      - name: check out the code
        uses: actions/checkout@v2.7.0
      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v3.1.2
        with:
          name: ${{ env.ARTIFACT_NAME }}
          path: .
